# Generated by Django 2.2.6 on 2019-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stop_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('vehicle_number', models.IntegerField()),
                ('route_number', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('estimated_load', models.IntegerField()),
                ('maximum_speed', models.IntegerField()),
                ('train_mileage', models.DecimalField(max_digits=7,decimal_places=7)),
                ('pattern_distance', models.DecimalField(max_digits=7,decimal_places=7)),
                ('location_distance', models.DecimalField(max_digits=7,decimal_places=7)),
                ('x_coordinate', models.DecimalField(max_digits=7,decimal_places=7)),
                ('y_coordinate', models.DecimalField(max_digits=7,decimal_places=7)),
                ('data_source', models.IntegerField()),
                ('schedule_status', models.IntegerField()),
                ('trip_id', models.IntegerField()),
            ],
        ),
    ]
