# Generated by Django 2.2.5 on 2019-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_stop',
            fields=[
                ('stop_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('stop_code', models.IntegerField(default=-1)),
                ('stop_name', models.CharField(default='none provided', max_length=100)),
                ('stop_desc', models.CharField(default='none provided', max_length=100)),
                ('stop_lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('stop_lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('zone_id', models.IntegerField(default=-1)),
                ('stop_url', models.CharField(default='none provided', max_length=100)),
                ('location_type', models.IntegerField(default=-1)),
                ('parent_station', models.CharField(default='none provided', max_length=100)),
                ('stop_timezone', models.CharField(default='none provided', max_length=100)),
                ('wheelchair_boarding', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name_plural': 'bus_stops',
            },
        ),
        migrations.CreateModel(
            name='stop_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(null=True)),
                ('vehicle_number', models.IntegerField(default=-1, null=True)),
                ('leave_time', models.IntegerField(default=-1, null=True)),
                ('train', models.IntegerField(default=-1, null=True)),
                ('badge', models.IntegerField(default=-1, null=True)),
                ('route_number', models.IntegerField(default=-1, null=True)),
                ('direction', models.IntegerField(default=-1, null=True)),
                ('service_key', models.CharField(max_length=1, null=True)),
                ('trip_number', models.IntegerField(default=-1, null=True)),
                ('stop_time', models.IntegerField(default=-1, null=True)),
                ('arrive_time', models.IntegerField(default=-1, null=True)),
                ('dwell', models.IntegerField(default=-1, null=True)),
                ('location_id', models.IntegerField(default=-1, null=True)),
                ('door', models.IntegerField(default=-1, null=True)),
                ('lift', models.IntegerField(default=-1, null=True)),
                ('ons', models.IntegerField(default=-1, null=True)),
                ('offs', models.IntegerField(default=-1, null=True)),
                ('estimated_load', models.IntegerField(default=-1, null=True)),
                ('maximum_speed', models.IntegerField(default=-1, null=True)),
                ('train_mileage', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('pattern_distance', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('location_distance', models.DecimalField(decimal_places=5, max_digits=11, null=True)),
                ('x_coordinate', models.DecimalField(decimal_places=5, default=-1, max_digits=11, null=True)),
                ('y_coordinate', models.DecimalField(decimal_places=5, default=-1, max_digits=11, null=True)),
                ('data_source', models.IntegerField(default=-1, null=True)),
                ('schedule_status', models.IntegerField(default=-1, null=True)),
                ('trip_id', models.IntegerField(default=-1, null=True)),
            ],
        ),
    ]
