# Generated by Django 2.2.5 on 2019-10-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, default=-1)),
                ('stop_code', models.IntegerField(default=-1)),
                ('stop_name', models.CharField(default='none provided', max_length=100)),
                ('stop_desc', models.CharField(default='none provided', max_length=100)),
                ('stop_lat', models.DecimalField(decimal_places=3, max_digits=7)),
                ('stop_lon', models.DecimalField(decimal_places=3, max_digits=7)),
                ('zone_id', models.IntegerField(default=-1)),
                ('stop_url', models.CharField(default='none provided', max_length=100)),
                ('location_type', models.IntegerField(default=-1)),
                ('parent_station', models.CharField(default='none provided', max_length=100)),
                ('stop_timezone', models.CharField(default='none provided', max_length=100)),
                ('wheelchair_boarding', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name_plural': 'bus_stops',
            },
        ),
        migrations.CreateModel(
            name='stop_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
