# Generated by Django 2.2.5 on 2019-10-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_stop',
            name='stop_id',
            field=models.IntegerField(default=-1),
        ),
    ]
