# Generated by Django 2.2.5 on 2019-10-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysMap', '0002_auto_20191013_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_stop',
            name='stop_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
