# Generated by Django 2.2.5 on 2019-10-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysMap', '0003_auto_20191014_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_stop',
            name='stop_lat',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bus_stop',
            name='stop_lon',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
    ]
