# Generated by Django 2.2.5 on 2019-10-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysMap', '0006_auto_20191014_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_stop',
            name='stop_lat',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='bus_stop',
            name='stop_lon',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
